### ISSUE TITLE
Create 3D height-field terrain background

### ISSUE THREAD

**Issue by DustinLim** [DustinLim/IN4152-game#6]
> The background of the game should be a 3D height‐field terrain (Exercise 3), which is procedurally generated [...] Optimally, you should create the illusion of an infinite mountainscape.

**Comment by Marlou16** [comment]
Op dit moment kan de landscape branch een tweedelige mountain ridge laten zien waarbij elke ridge een eigen functie kan meekrijgen en op een eigen snelheid beweegt.
Op dit moment is het nog wel nodig dat alle ridge functies een zelfde periode heeft!
